'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18046
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Infotjenester.Hressurs.Provider.Test.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2408;Andreas;Helgesen;1;
        '''2408;Pia;Andersen;1;
        '''2001;Anette;Helgesen;2;
        '''2408;Jesper;Andersen;1;
        '''1911;Arne;Hansen;1;
        '''2001;Lene;Helgesen;2;
        '''.
        '''</summary>
        Friend ReadOnly Property HRChild() As String
            Get
                Return ResourceManager.GetString("HRChild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Identifier;FirstName;MiddleName;LastName;ShortName;Gender;BirthDate;EmployeeNo;PersonalNo;Email;Street1;Street2;PostNo;Postarea;Phone;PhonePrivate;Mobile;Fax;BankAccount1;BankAccount2;DepartmentName;DepartmentNumber;SetAsLeader;EmployeeCategory;EmployeePosition;Nationality;NextOfKind;NextOfKindPhone;EmploymentStartDate;EmploymentPercent;EmploymentEndDate;IsActive;NearestLeaderIdentifier;
        '''1;Martin;;Helgesen;;1;24.08.1980;123;24088047326;mhe@infotjenester.no;Dronningensgate 82;;1723;Sarpsborg;;;97125917;;163 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HRPerson() As String
            Get
                Return ResourceManager.GetString("HRPerson", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to 4170;WF;Egil;;Bjerke;;1;04.01.1956;4170;04015642993;egil.bjerke@wideroe.no;Torvmyrvn 41;;;3170;SEM;NO; ; ; ;;;;425;;F;Flytekniker; ;;;;01.08.1986; ;1;;egil.bjerke@wideroe.no
        '''15260;WF;Jørn Gunnar;;Hansen;;1;10.02.1963;15260;10026328123; ; ;;; ; ; ; ; ; ;;;;045;;F;Sjef Stuertjenesten; ;;;;16.04.1999; ;1;;
        '''.
        '''</summary>
        Friend ReadOnly Property w_ansatte() As String
            Get
                Return ResourceManager.GetString("w_ansatte", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to 4170;WF;Egil;;Bjerke;;1;04.01.1956;4170;04015642993;egil.bjerke@wideroe.no;Torvmyrvn 41;;;3170;SEM;NO; ; ; ;;;;425;;F;Flytekniker; ;;;;01.08.1986; ;1;;egil.bjerke@wideroe.no
        '''6880;WF;John Agnar;;Hansen;;1;18.05.1955;6880;18055534302;john.agnar.hansen@wideroe.no;Kjelling;;;8120;NYGÅRDSJØEN;NO; ; ;004795714296;;;;602;;F;Flytekniker; ;;;;19.03.2001; ;1;;john.agnar.hansen@wideroe.no
        '''3459;WF;Reidar;;Johansen;;1;12.06.1954;3459;12065438117;reidar.johansen@wideroe.no;Trollmyra 28;;;8028;BODØ;NO; ; ; ;;;;419;;F;Et [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property WF_Personale_130625_1() As String
            Get
                Return ResourceManager.GetString("WF_Personale_130625_1", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
