'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18046
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Datastreamr.Framework.Test.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 05004800474800000795000   74071699270092702370345000000000926000000017000578000000017000578SCANDINAVIAN1172339950644OSLO         NO 301600000     1000N0421242 4 01927100503            AI        HANGER/VIDAR MR     092509OSLQ6C OSL                     60491771SCANDINA                  00000000000000000000000000000000000000000000000000022453812
        '''05004800474801000795000   74071699270092702370329000000000926000000290300578000000290300578SCANDINAVIAN1172339950642OSLO         NO 301600000     1000N0421222 4 01927 [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property FixedPosition_NoHeader() As String
            Get
                Return ResourceManager.GetString("FixedPosition_NoHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Identifier;FirstName;MiddleName;LastName;ShortName;Gender;BirthDate;EmployeeNo;PersonalNo;Email;Street1;Street2;PostNo;Postarea;Phone;PhonePrivate;Mobile;Fax;BankAccount1;BankAccount2;DepartmentName;DepartmentNumber;SetAsLeader;EmployeeCategory;EmployeePosition;Nationality;NextOfKind;NextOfKindPhone;EmploymentStartDate;EmploymentPercent;EmploymentEndDate;IsActive;NearestLeaderIdentifier;
        '''1;Martin;;Helgesen;;1;24.08.1980;123;24088047326;mhe@infotjenester.no;Dronningensgate 82;;1723;Sarpsborg;;;97125917;;163 [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property HRPerson() As String
            Get
                Return ResourceManager.GetString("HRPerson", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Identifier;CompanyIdentifier;FirstName;MiddleName;LastName;ShortName;Gender;BirthDate;EmployeeNo;PersonalNo;Email;Street1;Street2;Street3;PostNo;Postarea;CountryCode;Phone;PhonePrivate;Mobile;Fax;BankAccount1;BankAccount2;DepartmentIdentifier;SetAsLeader;EmployeeCategory;EmployeePosition;Nationality;NextOfKinFirstName;NextOfKinLastName;NextOfKinPhone;EmploymentStartDate;EmploymentEndDate;IsActive;SpecifiedLeaderIdentifier;Username
        '''2408;1234;Martin;Helge;Helgesen;Helgis;1;24.08.1980;2408;24088047326;martin@ [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property Middleware_FullPersonFile_WithHeader() As String
            Get
                Return ResourceManager.GetString("Middleware_FullPersonFile_WithHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @EmployeeNumber;@Name;@PersonalNo;@EMail;@Phone;@PhonePrivate;@PhoneMobile;@DepartmentNo;@AccountNo;@EmployeeCategoryName;@EmployeePositionName;@EmploymentStartDate;@EmploymentPercent;
        '''1962;Martin Helgesen;24088047326;test1@test.no;69971705;69157337;97125917;23;23;Fast stilling;FAGKONSULENT (FORRETNINGSUTVIKLING)               ;01.04.2007;100;
        '''166;TESTPERSON 2;24088047326;test2@test.no;;;;27;27;Fast stilling;DRIFTSDIREKTØR;05.08.2006;100;
        '''352;TESTPERSON 3;2408804732;test3@test.no;;;;27;27;Fast stilling;R [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property Semicolon_Header() As String
            Get
                Return ResourceManager.GetString("Semicolon_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1962;Martin Helgesen;24088047326;test1@test.no;69971705;69157337;97125917;23;23;Fast stilling;FAGKONSULENT (FORRETNINGSUTVIKLING)               ;01.04.2007;100;
        '''166;TESTPERSON 2;24088047326;test2@test.no;;;;27;27;Fast stilling;DRIFTSDIREKTØR;05.08.2006;100;
        '''352;TESTPERSON 3;2408804732;test3@test.no;;;;27;27;Fast stilling;REGIONSDIREKTØR;01.02.2010;100;.
        '''</summary>
        Public ReadOnly Property Semicolon_NoHeader() As String
            Get
                Return ResourceManager.GetString("Semicolon_NoHeader", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
