'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18033
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Datastreamr.Framework.Test.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 05004800474800000795000   74071699270092702370345000000000926000000017000578000000017000578SCANDINAVIAN1172339950644OSLO         NO 301600000     1000N0421242 4 01927100503            AI        HANGER/VIDAR MR     092509OSLQ6C OSL                     60491771SCANDINA                  00000000000000000000000000000000000000000000000000022453812
        '''05004800474801000795000   74071699270092702370329000000000926000000290300578000000290300578SCANDINAVIAN1172339950642OSLO         NO 301600000     1000N0421222 4 01927 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FixedPosition_NoHeader() As String
            Get
                Return ResourceManager.GetString("FixedPosition_NoHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @EmployeeNumber;@Name;@PersonalNo;@EMail;@Phone;@PhonePrivate;@PhoneMobile;@DepartmentNo;@AccountNo;@EmployeeCategoryName;@EmployeePositionName;@EmploymentStartDate;@EmploymentPercent;@EmploymentEndDate;
        '''1962;SOLVANG TROND;09035948934;trond.solvang@olavthon.no;;;;23;23;Fast stilling;FAGKONSULENT (FORRETNINGSUTVIKLING)               ;01.04.2007;100;
        '''166;LINDVALL ANDERS;31077041772;anders.lindvall@thonhotels.no;;;;27;27;Fast stilling;DRIFTSDIREKTØR;05.08.2006;100;
        '''352;BLOMBERG-NYGÅRD ANITA;05107148894;anit [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Semicolon_Header() As String
            Get
                Return ResourceManager.GetString("Semicolon_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1962;SOLVANG TROND;09035948934;trond.solvang@olavthon.no;;;;23;23;Fast stilling;FAGKONSULENT (FORRETNINGSUTVIKLING)               ;01.04.2007;100;
        '''166;LINDVALL ANDERS;31077041772;anders.lindvall@thonhotels.no;;;;27;27;Fast stilling;DRIFTSDIREKTØR;05.08.2006;100;
        '''352;BLOMBERG-NYGÅRD ANITA;05107148894;anita.blomberg-nygard@thonhotels.no;;;;27;27;Fast stilling;REGIONSDIREKTØR;01.02.2010;100;
        '''270;THOR ANNA;26047422891;annathor@thonhotels.no;23080178;;;33;27;Fast stilling;BOOKING &amp; DISTR.KONSULENT;23.02.2000; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Semicolon_NoHeader() As String
            Get
                Return ResourceManager.GetString("Semicolon_NoHeader", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
