
Public Class HRPerson
    Property Identifier As String
    Property CompanyIdentifier As String
    Property FirstName As String
    Property MiddleName As String
    Property LastName As String
    Property ShortName As String
    Property Gender As Integer
    Property BirthDate As String
    Property EmployeeNo As String
    Property PersonalNo As String
    Property Email As String
    Property Street1 As String
    Property Street2 As String
    Property Street3 As String
    Property PostNo As String
    Property Postarea As String
    Property CountryCode As String
    Property Phone As String
    Property PhonePrivate As String
    Property Mobile As String
    Property Fax As String
    Property BankAccount1 As String
    Property BankAccount2 As String
    Property DepartmentIdentifier As String
    Property SetAsLeader As String
    Property EmployeeCategory As String
    Property EmployeePosition As String
    Property Nationality As String
    Property NextOfKinFirstName As String
    Property NextOfKinLastName As String
    Property NextOfKinPhone As String
    Property EmploymentStartDate As String
    Property EmploymentEndDate As String
    Property IsActive As String
    Property SpecifiedLeaderIdentifier As String
    Property Username As String
End Class
